version: '3.9'

services:
  backend:
    build: .
    container_name: kavak_sales_bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
