BRAND_ABBREVIATIONS = {
    "vw": "Volkswagen",
    "lr": "Land Rover",
    "bmw": "BMW",
    "mb": "Mercedes-Benz",
    "chevy": "Chevrolet",
    "toy": "Toyota",
    "honda": "Honda",
    "kia": "KIA",
    "nissan": "Nissan",
    "audi": "Audi",
    "mazda": "Mazda",
}
STOPWORDS = {
    "un",
    "una",
    "el",
    "la",
    "los",
    "las",
    "quiero",
    "busco",
    "necesito",
    "deseo",
    "comprar",
}
MULTAS_KEYWORDS = [
    "multa",
    "multas",
    "infraccion",
    "infracciones",
    "placa",
    "tenencia",
    "adeudo",
    "adeudos",
    "tarjeta de circulacion",
    "licencia",
    "transito",
    "pago de placas",
    "verifica si debo",
    "debo pagar",
    "consultar placa",
]
TOKEN_SYNONYMS = {
    # Bluetooth
    "blutut": "bluetooth",
    "bluetooh": "bluetooth",
    "bluethot": "bluetooth",
    "bluetooth": "bluetooth",
    "blueto": "bluetooth",
    "blutooth": "bluetooth",
    "inalámbrico": "bluetooth",
    "inalambrico": "bluetooth",
    "con audifonos": "bluetooth",
    "manos libres": "bluetooth",
    # CarPlay
    "carplay": "car_play",
    "car play": "car_play",
    "car-play": "car_play",
    "iphone": "car_play",
    "conectar": "car_play",
    "conecto": "car_play",
    "conexión iphone": "car_play",
    "sin cables": "car_play",
    "celular": "car_play",
    "android auto": "car_play",
    "androidauto": "car_play",
    # Otros términos útiles (puedes expandir según tu contexto)
    "mazdas": "mazda",
    "bmws": "bmw",
    "audis": "audi",
    "nissanes": "nissan",
    "toyotas": "toyota",
    "kiaa": "kia",
    "kia": "kia",
    "carro": "auto",
    "coche": "auto",
    "vehiculo": "auto",
}

COLLOQUIAL_NUMBERS = {
    "toston": 50000,
    "medio millon": 500000,
    "medio millón": 500000,
    "un millon": 1000000,
    "un millón": 1000000,
    "1 millon": 1000000,
    "1 millón": 1000000,
    "cincuenta mil": 50000,
    "veinte mil": 20000,
    "treinta mil": 30000,
    "cuarenta mil": 40000,
}


RECOMMENDATION_PATTERNS = [
    "recomienda",
    "recomendar",
    "recomiéndame",
    "recomiendame",
    "sugiere",
    "sugerencia",
    "sugerirme",
    "qué auto",
    "que auto",
    "coche",
    "carro",
    "opción",
    "opciones",
    "sugerencias",
]
